services:
  - type: web
    name: chessdiary-stockfish
    env: python
    buildCommand: "apt-get update && apt-get install -y stockfish && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: STOCKFISH_PATH
        value: /usr/games/stockfish
    plan: free
